---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 600
  title: Shader Processor Input (SPI)
  data source:
    - metric_table:
        id: 601
        title: SPI Stats
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          GPU Busy:
            avg: AVG(GRBM_GUI_ACTIVE)
            min: MIN(GRBM_GUI_ACTIVE)
            max: MAX(GRBM_GUI_ACTIVE)
            unit: Cycles
            tips: 
          CS Busy:
            avg: AVG(SPI_CSN_BUSY)
            min: MIN(SPI_CSN_BUSY)
            max: MAX(SPI_CSN_BUSY)
            unit: Cycles
            tips: 
          SPI Busy:
            avg: AVG(GRBM_SPI_BUSY)
            min: MIN(GRBM_SPI_BUSY)
            max: MAX(GRBM_SPI_BUSY)
            unit: Cycles
            tips: 
          SQ Busy:
            avg: AVG(SQ_BUSY_CYCLES)
            min: MIN(SQ_BUSY_CYCLES)
            max: MAX(SQ_BUSY_CYCLES)
            unit: Cycles
            tips: 
          Dispatched Workgroups:
            avg: AVG(SPI_CSN_NUM_THREADGROUPS)
            min: MIN(SPI_CSN_NUM_THREADGROUPS)
            max: MAX(SPI_CSN_NUM_THREADGROUPS)
            unit: Workgroups
            tips: 
          Dispatched Wavefronts:
            avg: AVG(SPI_CSN_WAVE)
            min: MIN(SPI_CSN_WAVE)
            max: MAX(SPI_CSN_WAVE)
            unit: Wavefronts
            tips: 
          Wave Alloc Failed:
            avg: AVG(SPI_RA_REQ_NO_ALLOC)
            min: MIN(SPI_RA_REQ_NO_ALLOC)
            max: MAX(SPI_RA_REQ_NO_ALLOC)
            unit: Cycles
            tips: 
          Wave Alloc Failed - CS:
            avg: AVG(SPI_RA_REQ_NO_ALLOC_CSN)
            min: MIN(SPI_RA_REQ_NO_ALLOC_CSN)
            max: MAX(SPI_RA_REQ_NO_ALLOC_CSN)
            unit: Cycles
            tips:

    - metric_table:
        id: 602
        title: SPI Resource Allocation
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Wave request Failed (CS):
            avg: AVG(SPI_RA_REQ_NO_ALLOC_CSN)
            min: MIN(SPI_RA_REQ_NO_ALLOC_CSN)
            max: MAX(SPI_RA_REQ_NO_ALLOC_CSN)
            unit: Cycles
            tips: 
          CS Stall:
            avg: AVG(SPI_RA_RES_STALL_CSN)
            min: MIN(SPI_RA_RES_STALL_CSN)
            max: MAX(SPI_RA_RES_STALL_CSN)
            unit: Cycles
            tips: 
          CS Stall Rate:
            avg: AVG((((100 * SPI_RA_RES_STALL_CSN) / GRBM_SPI_BUSY) if (GRBM_SPI_BUSY !=
              0) else None))
            min: MIN((((100 * SPI_RA_RES_STALL_CSN) / GRBM_SPI_BUSY) if (GRBM_SPI_BUSY !=
              0) else None))
            max: MAX((((100 * SPI_RA_RES_STALL_CSN) / GRBM_SPI_BUSY) if (GRBM_SPI_BUSY !=
              0) else None))
            unit: pct
            tips: 
          Scratch Stall:
            avg: AVG(SPI_RA_TMP_STALL_CSN)
            min: MIN(SPI_RA_TMP_STALL_CSN)
            max: MAX(SPI_RA_TMP_STALL_CSN)
            unit: Cycles
            tips: 
          Insufficient SIMD Waveslots:
            avg: AVG(SPI_RA_WAVE_SIMD_FULL_CSN)
            min: MIN(SPI_RA_WAVE_SIMD_FULL_CSN)
            max: MAX(SPI_RA_WAVE_SIMD_FULL_CSN)
            unit: SIMD
            tips: 
          Insufficient SIMD VGPRs:
            avg: AVG(SPI_RA_VGPR_SIMD_FULL_CSN)
            min: MIN(SPI_RA_VGPR_SIMD_FULL_CSN)
            max: MAX(SPI_RA_VGPR_SIMD_FULL_CSN)
            unit: SIMD
            tips: 
          Insufficient SIMD SGPRs:
            avg: AVG(SPI_RA_SGPR_SIMD_FULL_CSN)
            min: MIN(SPI_RA_SGPR_SIMD_FULL_CSN)
            max: MAX(SPI_RA_SGPR_SIMD_FULL_CSN)
            unit: SIMD
            tips: 
          Insufficient CU LDS:
            avg: AVG(SPI_RA_LDS_CU_FULL_CSN)
            min: MIN(SPI_RA_LDS_CU_FULL_CSN)
            max: MAX(SPI_RA_LDS_CU_FULL_CSN)
            unit: CU
            tips: 
          Insufficient CU Barries:
            avg: AVG(SPI_RA_BAR_CU_FULL_CSN)
            min: MIN(SPI_RA_BAR_CU_FULL_CSN)
            max: MAX(SPI_RA_BAR_CU_FULL_CSN)
            unit: CU
            tips: 
          Insufficient Bulky Resource:
            avg: AVG(SPI_RA_BULKY_CU_FULL_CSN)
            min: MIN(SPI_RA_BULKY_CU_FULL_CSN)
            max: MAX(SPI_RA_BULKY_CU_FULL_CSN)
            unit: CU
            tips: 
          Reach CU Threadgroups Limit:
            avg: AVG(SPI_RA_TGLIM_CU_FULL_CSN)
            min: MIN(SPI_RA_TGLIM_CU_FULL_CSN)
            max: MAX(SPI_RA_TGLIM_CU_FULL_CSN)
            unit: Cycles
            tips: 
          Reach CU Wave Limit:
            avg: AVG(SPI_RA_WVLIM_STALL_CSN)
            min: MIN(SPI_RA_WVLIM_STALL_CSN)
            max: MAX(SPI_RA_WVLIM_STALL_CSN)
            unit: Cycles
            tips: 
          VGPR Writes:
            avg: AVG((((4 * SPI_VWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            min: MIN((((4 * SPI_VWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            max: MAX((((4 * SPI_VWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            unit: Cycles/wave
            tips: 
          SGPR Writes:
            avg: AVG((((1 * SPI_SWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            min: MIN((((1 * SPI_SWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            max: MAX((((1 * SPI_SWC_CSC_WR) / SPI_CSN_WAVE) if (SPI_CSN_WAVE != 0) else
              None))
            unit: Cycles/wave
            tips:
