---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 1000
  title: Compute Units - Instruction Mix
  data source:
    - metric_table:
        id: 1001
        title: Instruction Mix
        header:
          metric: Metric
          count: Count
          unit: Unit
          tips: Tips
        metric:
          VALU - Vector:
            count: AVG(((SQ_INSTS_VALU - SQ_INSTS_MFMA) / $denom))
            unit: (instr + $normUnit)
            tips: 
          VMEM:
            count: AVG(((SQ_INSTS_VMEM - SQ_INSTS_FLAT_LDS_ONLY) / $denom))
            unit: (instr + $normUnit)
            tips: 
          LDS:
            count: AVG((SQ_INSTS_LDS / $denom))
            unit: (instr + $normUnit)
            tips: 
          VALU - MFMA:
            count: None # No HW module
            unit: (instr + $normUnit)
            tips: 
          SALU:
            count: AVG((SQ_INSTS_SALU / $denom))
            unit: (instr + $normUnit)
            tips: 
          SMEM:
            count: AVG((SQ_INSTS_SMEM / $denom))
            unit: (instr + $normUnit)
            tips: 
          Branch:
            count: AVG((SQ_INSTS_BRANCH / $denom))
            unit: (instr + $normUnit)
            tips: 
          GDS:
            count: AVG((SQ_INSTS_GDS / $denom))
            unit: (instr + $normUnit)
            tips: 

    - metric_table:
        id: 1002
        title: VALU Arithmetic Instr Mix
        header:
          metric: Metric
          count: Count
          unit: Unit
          tips: Tips
        metric:
          INT-32:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          INT-64:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F16-ADD:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F16-Mult:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F16-FMA:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F16-Trans:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F32-ADD:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F32-Mult:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F32-FMA:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F32-Trans:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F64-ADD:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F64-Mult:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F64-FMA:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          F64-Trans:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:
          Conversion:
            count: None # No perf counter
            unit: (instr + $normUnit)
            tips:

    - metric_table:
        id: 1003
        title: VMEM Instr Mix
        header:
          type: Type
          count: Count
          tips: Tips
        metric:
          Buffer Instr:
            count: AVG((TA_BUFFER_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Read:
            count: AVG((TA_BUFFER_READ_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Write:
            count: AVG((TA_BUFFER_WRITE_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Atomic:
            count: AVG((TA_BUFFER_ATOMIC_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Instr:
            count: AVG((TA_FLAT_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Read:
            count: AVG((TA_FLAT_READ_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Write:
            count: AVG((TA_FLAT_WRITE_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Atomic:
            count: AVG((TA_FLAT_ATOMIC_WAVEFRONTS_sum / $denom))
            tips: 

    - metric_table:
        id: 1004
        title: MFMA Arithmetic Instr Mix
        header:
          type: Type
          count: Count
          tips: Tips
        metric:
          MFMA-I8:
            count: None # No HW module
            tips:
          MFMA-F16:
            count: None # No HW module
            tips:
          MFMA-BF16:
            count: None # No HW module
            tips:
          MFMA-F32:
            count: None # No HW module
            tips:
          MFMA-F64:
            count: None # No HW module
            tips:
