---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 1100
  title: Compute Units - Compute Pipeline
  data source:
    - metric_table:
        id: 1101
        title: Speed-of-Light
        header:
          metric: Metric
          value: Value
          tips: Tips
        metric:
          valu_flops_pop:
            value: None # No perf counter
            tips:
          mfma_flops_bf16_pop:
            value: None # No perf counter
            tips:
          mfma_flops_f16_pop:
            value: None # No perf counter
            tips:
          mfma_flops_f32_pop:
            value: None # No perf counter
            tips:
          mfma_flops_f64_pop:
            value: None # No perf counter
            tips:
          mfma_flops_i8_pop:
            value: None # No perf counter
            tips:

    - metric_table:
        id: 1102
        title: Pipeline Stats
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          IPC (Avg):
            avg: AVG((SQ_INSTS / SQ_BUSY_CU_CYCLES))
            min: MIN((SQ_INSTS / SQ_BUSY_CU_CYCLES))
            max: MAX((SQ_INSTS / SQ_BUSY_CU_CYCLES))
            unit: Instr/cycle
            tips: 
          IPC (Issue):
            avg: AVG(((((((((SQ_INSTS_VALU + SQ_INSTS_VMEM) + SQ_INSTS_SALU) + SQ_INSTS_SMEM)
              + SQ_INSTS_GDS) + SQ_INSTS_BRANCH) + SQ_INSTS_SENDMSG) + SQ_INSTS_VSKIPPED)
              / SQ_ACTIVE_INST_ANY))
            min: MIN(((((((((SQ_INSTS_VALU + SQ_INSTS_VMEM) + SQ_INSTS_SALU) + SQ_INSTS_SMEM)
              + SQ_INSTS_GDS) + SQ_INSTS_BRANCH) + SQ_INSTS_SENDMSG) + SQ_INSTS_VSKIPPED)
              / SQ_ACTIVE_INST_ANY))
            max: MAX(((((((((SQ_INSTS_VALU + SQ_INSTS_VMEM) + SQ_INSTS_SALU) + SQ_INSTS_SMEM)
              + SQ_INSTS_GDS) + SQ_INSTS_BRANCH) + SQ_INSTS_SENDMSG) + SQ_INSTS_VSKIPPED)
              / SQ_ACTIVE_INST_ANY))
            unit: Instr/cycle
            tips: 
          SALU Util:
            avg: AVG((((100 * SQ_ACTIVE_INST_SCA) / GRBM_GUI_ACTIVE) / $numCU))
            min: MIN((((100 * SQ_ACTIVE_INST_SCA) / GRBM_GUI_ACTIVE) / $numCU))
            max: MAX((((100 * SQ_ACTIVE_INST_SCA) / GRBM_GUI_ACTIVE) / $numCU))
            unit: pct
            tips: 
          VALU Util:
            avg: AVG((((100 * SQ_ACTIVE_INST_VALU) / GRBM_GUI_ACTIVE) / $numCU))
            min: MIN((((100 * SQ_ACTIVE_INST_VALU) / GRBM_GUI_ACTIVE) / $numCU))
            max: MAX((((100 * SQ_ACTIVE_INST_VALU) / GRBM_GUI_ACTIVE) / $numCU))
            unit: pct
            tips: 
          VALU Active Threads:
            avg: AVG(((SQ_THREAD_CYCLES_VALU / SQ_ACTIVE_INST_VALU) if (SQ_ACTIVE_INST_VALU
              != 0) else None))
            min: MIN(((SQ_THREAD_CYCLES_VALU / SQ_ACTIVE_INST_VALU) if (SQ_ACTIVE_INST_VALU
              != 0) else None))
            max: MAX(((SQ_THREAD_CYCLES_VALU / SQ_ACTIVE_INST_VALU) if (SQ_ACTIVE_INST_VALU
              != 0) else None))
            unit: Threads
            tips: 
          MFMA Util:
            avg: None # No HW module
            min: None # No HW module
            max: None # No HW module
            unit: pct
            tips:
          MFMA Instr Cycles:
            avg: None # No HW module
            min: None # No HW module
            max: None # No HW module
            unit: cycles/instr
            tips:

    - metric_table:
        id: 1103
        title: Arithmetic Operations
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          FLOPs (Total):
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:
          INT8 OPs:
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:
          F16 OPs:
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:
          BF16 OPs:
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:
          F32 OPs:
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:
          F64 OPs:
            avg: None # No perf counter
            min: None # No perf counter
            max: None # No perf counter
            unit: (OPs  + $normUnit)
            tips:


