---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 1300
  title: Instruction Cache
  data source:
    - metric_table:
        id: 1301
        title: Speed-of-Light
        header:
          metric: Metric
          value: Value
          tips: Tips
        metric:
          Bandwidth:
            value: AVG(((SQC_ICACHE_REQ * 100000) / (($sclk * $numSQC)
              * (EndNs - BeginNs))))
            tips: 
          Cache Hit:
            value: AVG(((SQC_ICACHE_HITS * 100) / ((SQC_ICACHE_HITS + SQC_ICACHE_MISSES)
              + SQC_ICACHE_MISSES_DUPLICATE)))
            tips: 

    - metric_table:
        id: 1302
        title: Instruction Cache Accesses
        header:
          metric: L1I Metric
          mean: Mean
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Req:
            mean: AVG((SQC_ICACHE_REQ / $denom))
            min: MIN((SQC_ICACHE_REQ / $denom))
            max: MAX((SQC_ICACHE_REQ / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Hits:
            mean: AVG((SQC_ICACHE_HITS / $denom))
            min: MIN((SQC_ICACHE_HITS / $denom))
            max: MAX((SQC_ICACHE_HITS / $denom))
            unit: (Hits  + $normUnit)
            tips: 
          Misses - Non Duplicated:
            mean: AVG((SQC_ICACHE_MISSES / $denom))
            min: MIN((SQC_ICACHE_MISSES / $denom))
            max: MAX((SQC_ICACHE_MISSES / $denom))
            unit: (Misses  + $normUnit)
            tips: 
          Misses - Duplicated:
            mean: AVG((SQC_ICACHE_MISSES_DUPLICATE / $denom))
            min: MIN((SQC_ICACHE_MISSES_DUPLICATE / $denom))
            max: MAX((SQC_ICACHE_MISSES_DUPLICATE / $denom))
            unit: (Misses  + $normUnit)
            tips: 
          Cache Hit:
            mean: AVG(((100 * SQC_ICACHE_HITS) / ((SQC_ICACHE_HITS + SQC_ICACHE_MISSES)
              + SQC_ICACHE_MISSES_DUPLICATE)))
            min: MIN(((100 * SQC_ICACHE_HITS) / ((SQC_ICACHE_HITS + SQC_ICACHE_MISSES) +
              SQC_ICACHE_MISSES_DUPLICATE)))
            max: MAX(((100 * SQC_ICACHE_HITS) / ((SQC_ICACHE_HITS + SQC_ICACHE_MISSES) +
              SQC_ICACHE_MISSES_DUPLICATE)))
            unit: pct
            tips: 
