---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 1700
  title: L2 Cache
  data source:
    - metric_table:
        id: 1701
        title: Speed-of-Light
        header:
          metric: Metric
          value: Value
          unit: Unit
          tips: Tips
        metric:
          L2 Util:
            value: AVG(((TCC_BUSY_sum * 100) / (TO_INT($L2Banks) * GRBM_GUI_ACTIVE)))
            unit: pct
            tips: 
          Cache Hit:
            value: AVG((((100 * TCC_HIT_sum) / (TCC_HIT_sum + TCC_MISS_sum)) if ((TCC_HIT_sum
              + TCC_MISS_sum) != 0) else 0))
            unit: pct
            tips: 
          L2-EA Rd BW:
            value: AVG((((TCC_EA_RDREQ_32B_sum * 32) + ((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum)
              * 64)) / (EndNs - BeginNs)))
            unit: GB/s
            tips: 
          L2-EA Wr BW:
            value: AVG((((TCC_EA_WRREQ_64B_sum * 64) + ((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum)
              * 32)) / (EndNs - BeginNs)))
            unit: GB/s
            tips: 

    - metric_table:
        id: 1702
        title: L2 - Fabric Transactions
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Read BW:
            avg: AVG((((TCC_EA_RDREQ_32B_sum * 32) + ((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum)
              * 64)) / $denom))
            min: MIN((((TCC_EA_RDREQ_32B_sum * 32) + ((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum)
              * 64)) / $denom))
            max: MAX((((TCC_EA_RDREQ_32B_sum * 32) + ((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum)
              * 64)) / $denom))
            unit: (Bytes  + $normUnit)
            tips: 
          Write BW:
            avg: AVG((((TCC_EA_WRREQ_64B_sum * 64) + ((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum)
              * 32)) / $denom))
            min: MIN((((TCC_EA_WRREQ_64B_sum * 64) + ((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum)
              * 32)) / $denom))
            max: MAX((((TCC_EA_WRREQ_64B_sum * 64) + ((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum)
              * 32)) / $denom))
            unit: (Bytes  + $normUnit)
            tips: 
          Read (32B):
            avg: AVG((TCC_EA_RDREQ_32B_sum / $denom))
            min: MIN((TCC_EA_RDREQ_32B_sum / $denom))
            max: MAX((TCC_EA_RDREQ_32B_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read (Uncached 32B):
            avg: AVG((TCC_EA_RD_UNCACHED_32B_sum / $denom))
            min: MIN((TCC_EA_RD_UNCACHED_32B_sum / $denom))
            max: MAX((TCC_EA_RD_UNCACHED_32B_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read (64B):
            avg: AVG(((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum) / $denom))
            min: MIN(((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum) / $denom))
            max: MAX(((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum) / $denom))
            unit: (Req  + $normUnit)
            tips: 
          HBM Read:
            avg: AVG((TCC_EA_RDREQ_DRAM_sum / $denom))
            min: MIN((TCC_EA_RDREQ_DRAM_sum / $denom))
            max: MAX((TCC_EA_RDREQ_DRAM_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write (32B):
            avg: AVG(((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum) / $denom))
            min: MIN(((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum) / $denom))
            max: MAX(((TCC_EA_WRREQ_sum - TCC_EA_WRREQ_64B_sum) / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write (Uncached 32B):
            avg: AVG((TCC_EA_WR_UNCACHED_32B_sum / $denom))
            min: MIN((TCC_EA_WR_UNCACHED_32B_sum / $denom))
            max: MAX((TCC_EA_WR_UNCACHED_32B_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write (64B):
            avg: AVG((TCC_EA_WRREQ_64B_sum / $denom))
            min: MIN((TCC_EA_WRREQ_64B_sum / $denom))
            max: MAX((TCC_EA_WRREQ_64B_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          HBM Write:
            avg: AVG((TCC_EA_WRREQ_DRAM_sum / $denom))
            min: MIN((TCC_EA_WRREQ_DRAM_sum / $denom))
            max: MAX((TCC_EA_WRREQ_DRAM_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read Latency:
            avg: AVG(((TCC_EA_RDREQ_LEVEL_sum / TCC_EA_RDREQ_sum) if (TCC_EA_RDREQ_sum !=
              0) else None))
            min: MIN(((TCC_EA_RDREQ_LEVEL_sum / TCC_EA_RDREQ_sum) if (TCC_EA_RDREQ_sum !=
              0) else None))
            max: MAX(((TCC_EA_RDREQ_LEVEL_sum / TCC_EA_RDREQ_sum) if (TCC_EA_RDREQ_sum !=
              0) else None))
            unit: Cycles
            tips: 
          Write Latency:
            avg: AVG(((TCC_EA_WRREQ_LEVEL_sum / TCC_EA_WRREQ_sum) if (TCC_EA_WRREQ_sum !=
              0) else None))
            min: MIN(((TCC_EA_WRREQ_LEVEL_sum / TCC_EA_WRREQ_sum) if (TCC_EA_WRREQ_sum !=
              0) else None))
            max: MAX(((TCC_EA_WRREQ_LEVEL_sum / TCC_EA_WRREQ_sum) if (TCC_EA_WRREQ_sum !=
              0) else None))
            unit: Cycles
            tips: 
          Atomic Latency:
            avg: AVG(((TCC_EA_ATOMIC_LEVEL_sum / TCC_EA_ATOMIC_sum) if (TCC_EA_ATOMIC_sum
              != 0) else None))
            min: MIN(((TCC_EA_ATOMIC_LEVEL_sum / TCC_EA_ATOMIC_sum) if (TCC_EA_ATOMIC_sum
              != 0) else None))
            max: MAX(((TCC_EA_ATOMIC_LEVEL_sum / TCC_EA_ATOMIC_sum) if (TCC_EA_ATOMIC_sum
              != 0) else None))
            unit: Cycles
            tips: 
          Read Stall:
            avg: AVG((((100 * ((TCC_EA_RDREQ_IO_CREDIT_STALL_sum + TCC_EA_RDREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            min: MIN((((100 * ((TCC_EA_RDREQ_IO_CREDIT_STALL_sum + TCC_EA_RDREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            max: MAX((((100 * ((TCC_EA_RDREQ_IO_CREDIT_STALL_sum + TCC_EA_RDREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            unit: pct
            tips: 
          Write Stall:
            avg: AVG((((100 * ((TCC_EA_WRREQ_IO_CREDIT_STALL_sum + TCC_EA_WRREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            min: MIN((((100 * ((TCC_EA_WRREQ_IO_CREDIT_STALL_sum + TCC_EA_WRREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            max: MAX((((100 * ((TCC_EA_WRREQ_IO_CREDIT_STALL_sum + TCC_EA_WRREQ_GMI_CREDIT_STALL_sum)
              + TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum)) / TCC_BUSY_sum) if (TCC_BUSY_sum !=
              0) else None))
            unit: pct
            tips: 

    - metric_table:
        id: 1703
        title: L2 Cache Accesses
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Req:
            avg: AVG((TCC_REQ_sum / $denom))
            min: MIN((TCC_REQ_sum / $denom))
            max: MAX((TCC_REQ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Streaming Req:
            avg: AVG((TCC_STREAMING_REQ_sum / $denom))
            min: MIN((TCC_STREAMING_REQ_sum / $denom))
            max: MAX((TCC_STREAMING_REQ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read Req:
            avg: AVG((TCC_READ_sum / $denom))
            min: MIN((TCC_READ_sum / $denom))
            max: MAX((TCC_READ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write Req:
            avg: AVG((TCC_WRITE_sum / $denom))
            min: MIN((TCC_WRITE_sum / $denom))
            max: MAX((TCC_WRITE_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Atomic Req:
            avg: AVG((TCC_ATOMIC_sum / $denom))
            min: MIN((TCC_ATOMIC_sum / $denom))
            max: MAX((TCC_ATOMIC_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Probe Req:
            avg: AVG((TCC_PROBE_sum / $denom))
            min: MIN((TCC_PROBE_sum / $denom))
            max: MAX((TCC_PROBE_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Hits:
            avg: AVG((TCC_HIT_sum / $denom))
            min: MIN((TCC_HIT_sum / $denom))
            max: MAX((TCC_HIT_sum / $denom))
            unit: (Hits  + $normUnit)
            tips: 
          Misses:
            avg: AVG((TCC_MISS_sum / $denom))
            min: MIN((TCC_MISS_sum / $denom))
            max: MAX((TCC_MISS_sum / $denom))
            unit: (Misses  + $normUnit)
            tips: 
          Cache Hit:
            avg: AVG((((100 * TCC_HIT_sum) / (TCC_HIT_sum + TCC_MISS_sum)) if ((TCC_HIT_sum
              + TCC_MISS_sum) != 0) else None))
            min: MIN((((100 * TCC_HIT_sum) / (TCC_HIT_sum + TCC_MISS_sum)) if ((TCC_HIT_sum
              + TCC_MISS_sum) != 0) else None))
            max: MAX((((100 * TCC_HIT_sum) / (TCC_HIT_sum + TCC_MISS_sum)) if ((TCC_HIT_sum
              + TCC_MISS_sum) != 0) else None))
            unit: pct
            tips: 
          Writeback:
            avg: AVG((TCC_WRITEBACK_sum / $denom))
            min: MIN((TCC_WRITEBACK_sum / $denom))
            max: MAX((TCC_WRITEBACK_sum / $denom))
            unit: ( + $normUnit)
            tips: 
          NC Req:
            avg: AVG((TCC_NC_REQ_sum / $denom))
            min: MIN((TCC_NC_REQ_sum / $denom))
            max: MAX((TCC_NC_REQ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          UC Req:
            avg: AVG((TCC_UC_REQ_sum / $denom))
            min: MIN((TCC_UC_REQ_sum / $denom))
            max: MAX((TCC_UC_REQ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          CC Req:
            avg: AVG((TCC_CC_REQ_sum / $denom))
            min: MIN((TCC_CC_REQ_sum / $denom))
            max: MAX((TCC_CC_REQ_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          RW Req:
            avg: None # No HW module
            min: None # No HW module
            max: None # No HW module
            unit: (Req  + $normUnit)
            tips: 
          Writeback (Normal):
            avg: AVG((TCC_NORMAL_WRITEBACK_sum / $denom))
            min: MIN((TCC_NORMAL_WRITEBACK_sum / $denom))
            max: MAX((TCC_NORMAL_WRITEBACK_sum / $denom))
            unit: ( + $normUnit)
            tips: 
          Writeback (TC Req):
            avg: AVG((TCC_ALL_TC_OP_WB_WRITEBACK_sum / $denom))
            min: MIN((TCC_ALL_TC_OP_WB_WRITEBACK_sum / $denom))
            max: MAX((TCC_ALL_TC_OP_WB_WRITEBACK_sum / $denom))
            unit: ( + $normUnit)
            tips: 
          Evict (Normal):
            avg: AVG((TCC_NORMAL_EVICT_sum / $denom))
            min: MIN((TCC_NORMAL_EVICT_sum / $denom))
            max: MAX((TCC_NORMAL_EVICT_sum / $denom))
            unit: ( + $normUnit)
            tips: 
          Evict (TC Req):
            avg: AVG((TCC_ALL_TC_OP_INV_EVICT_sum / $denom))
            min: MIN((TCC_ALL_TC_OP_INV_EVICT_sum / $denom))
            max: MAX((TCC_ALL_TC_OP_INV_EVICT_sum / $denom))
            unit: ( + $normUnit)
            tips: 

    - metric_table:
        id: 1704
        title: L2 - EA Interface Stalls
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Read - Remote Socket Stall:
            avg: AVG((TCC_EA_RDREQ_IO_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_RDREQ_IO_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_RDREQ_IO_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read - Peer GCD Stall:
            avg: AVG((TCC_EA_RDREQ_GMI_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_RDREQ_GMI_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_RDREQ_GMI_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Read - HBM Stall:
            avg: AVG((TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_RDREQ_DRAM_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write - Remote Socket Stall:
            avg: AVG((TCC_EA_WRREQ_IO_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_WRREQ_IO_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_WRREQ_IO_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write - Peer GCD Stall:
            avg: AVG((TCC_EA_WRREQ_GMI_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_WRREQ_GMI_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_WRREQ_GMI_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write - HBM Stall:
            avg: AVG((TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum / $denom))
            min: MIN((TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum / $denom))
            max: MAX((TCC_EA_WRREQ_DRAM_CREDIT_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
          Write - Credit Starvation:
            avg: AVG((TCC_TOO_MANY_EA_WRREQS_STALL_sum / $denom))
            min: MIN((TCC_TOO_MANY_EA_WRREQS_STALL_sum / $denom))
            max: MAX((TCC_TOO_MANY_EA_WRREQS_STALL_sum / $denom))
            unit: (Req  + $normUnit)
            tips: 
