---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 500
  title: Command Processor (CPC/CPF)
  data source:
    - metric_table:
        id: 501
        title: Command Processor Fetcher
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          GPU Busy Cycles:
            avg: AVG(GRBM_GUI_ACTIVE)
            min: MIN(GRBM_GUI_ACTIVE)
            max: MAX(GRBM_GUI_ACTIVE)
            unit: Cycles/Kernel
            tips: 
          CPF Busy:
            avg: AVG(CPF_CPF_STAT_BUSY)
            min: MIN(CPF_CPF_STAT_BUSY)
            max: MAX(CPF_CPF_STAT_BUSY)
            unit: Cycles/Kernel
            tips: 
          CPF Util:
            avg: AVG((((100 * CPF_CPF_STAT_BUSY) / (CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE))
              if ((CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE) != 0) else None))
            min: MIN((((100 * CPF_CPF_STAT_BUSY) / (CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE))
              if ((CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE) != 0) else None))
            max: MAX((((100 * CPF_CPF_STAT_BUSY) / (CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE))
              if ((CPF_CPF_STAT_BUSY + CPF_CPF_STAT_IDLE) != 0) else None))
            unit: pct
            tips: 
          CPF Stall:
            avg: AVG((((100 * CPF_CPF_STAT_STALL) / CPF_CPF_STAT_BUSY) if (CPF_CPF_STAT_BUSY
              != 0) else None))
            min: MIN((((100 * CPF_CPF_STAT_STALL) / CPF_CPF_STAT_BUSY) if (CPF_CPF_STAT_BUSY
              != 0) else None))
            max: MAX((((100 * CPF_CPF_STAT_STALL) / CPF_CPF_STAT_BUSY) if (CPF_CPF_STAT_BUSY
              != 0) else None))
            unit: Cycles/Kernel
            tips: 
          L2Cache Intf Busy:
            avg: AVG(CPF_CPF_TCIU_BUSY)
            min: MIN(CPF_CPF_TCIU_BUSY)
            max: MAX(CPF_CPF_TCIU_BUSY)
            unit: Cycles/Kernel
            tips: 
          L2Cache Intf Util:
            avg: AVG((((100 * CPF_CPF_TCIU_BUSY) / (CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE))
              if ((CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE) != 0) else None))
            min: MIN((((100 * CPF_CPF_TCIU_BUSY) / (CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE))
              if ((CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE) != 0) else None))
            max: MAX((((100 * CPF_CPF_TCIU_BUSY) / (CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE))
              if ((CPF_CPF_TCIU_BUSY + CPF_CPF_TCIU_IDLE) != 0) else None))
            unit: pct
            tips: 
          L2Cache Intf Stall:
            avg: AVG((((100 * CPF_CPF_TCIU_STALL) / CPF_CPF_TCIU_BUSY) if (CPF_CPF_TCIU_BUSY
              != 0) else None))
            min: MIN((((100 * CPF_CPF_TCIU_STALL) / CPF_CPF_TCIU_BUSY) if (CPF_CPF_TCIU_BUSY
              != 0) else None))
            max: MAX((((100 * CPF_CPF_TCIU_STALL) / CPF_CPF_TCIU_BUSY) if (CPF_CPF_TCIU_BUSY
              != 0) else None))
            unit: pct
            tips: 
          UTCL1 Stall:
            avg: AVG(CPF_CMP_UTCL1_STALL_ON_TRANSLATION)
            min: MIN(CPF_CMP_UTCL1_STALL_ON_TRANSLATION)
            max: MAX(CPF_CMP_UTCL1_STALL_ON_TRANSLATION)
            unit: Cycles/Kernel
            tips: 

    - metric_table:
        id: 502
        title: Command Processor Compute
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          GPU Busy Cycles:
            avg: AVG(GRBM_GUI_ACTIVE)
            min: MIN(GRBM_GUI_ACTIVE)
            max: MAX(GRBM_GUI_ACTIVE)
            unit: Cycles
            tips: 
          CPC Busy Cycles:
            avg: AVG(CPC_CPC_STAT_BUSY)
            min: MIN(CPC_CPC_STAT_BUSY)
            max: MAX(CPC_CPC_STAT_BUSY)
            unit: Cycles
            tips: 
          CPC Util:
            avg: AVG((((100 * CPC_CPC_STAT_BUSY) / (CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE))
              if ((CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE) != 0) else None))
            min: MIN((((100 * CPC_CPC_STAT_BUSY) / (CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE))
              if ((CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE) != 0) else None))
            max: MAX((((100 * CPC_CPC_STAT_BUSY) / (CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE))
              if ((CPC_CPC_STAT_BUSY + CPC_CPC_STAT_IDLE) != 0) else None))
            unit: pct
            tips: 
          CPC Stall Cycles:
            avg: AVG(CPC_CPC_STAT_STALL)
            min: MIN(CPC_CPC_STAT_STALL)
            max: MAX(CPC_CPC_STAT_STALL)
            unit: Cycles
            tips: 
          CPC Stall Rate:
            avg: AVG((((100 * CPC_CPC_STAT_STALL) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            min: MIN((((100 * CPC_CPC_STAT_STALL) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            max: MAX((((100 * CPC_CPC_STAT_STALL) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            unit: pct
            tips: 
          CPC Packet Decoding:
            avg: AVG(CPC_ME1_BUSY_FOR_PACKET_DECODE)
            min: MIN(CPC_ME1_BUSY_FOR_PACKET_DECODE)
            max: MAX(CPC_ME1_BUSY_FOR_PACKET_DECODE)
            unit: Cycles
            tips: 
          SPI Intf Busy Cycles:
            avg: AVG(CPC_ME1_DC0_SPI_BUSY)
            min: MIN(CPC_ME1_DC0_SPI_BUSY)
            max: MAX(CPC_ME1_DC0_SPI_BUSY)
            unit: Cycles
            tips: 
          SPI Intf Util:
            avg: AVG((((100 * CPC_ME1_DC0_SPI_BUSY) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            min: MIN((((100 * CPC_ME1_DC0_SPI_BUSY) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            max: MAX((((100 * CPC_ME1_DC0_SPI_BUSY) / CPC_CPC_STAT_BUSY) if (CPC_CPC_STAT_BUSY
              != 0) else None))
            unit: pct
            tips: 
          L2Cache Intf Util:
            avg: AVG((((100 * CPC_CPC_TCIU_BUSY) / (CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE))
              if ((CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE) != 0) else None))
            min: MIN((((100 * CPC_CPC_TCIU_BUSY) / (CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE))
              if ((CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE) != 0) else None))
            max: MAX((((100 * CPC_CPC_TCIU_BUSY) / (CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE))
              if ((CPC_CPC_TCIU_BUSY + CPC_CPC_TCIU_IDLE) != 0) else None))
            unit: pct
            tips: 
          UTCL1 Stall Cycles:
            avg: AVG(CPC_UTCL1_STALL_ON_TRANSLATION)
            min: MIN(CPC_UTCL1_STALL_ON_TRANSLATION)
            max: MAX(CPC_UTCL1_STALL_ON_TRANSLATION)
            unit: Cycles
            tips: 
          UTCL2 Intf Busy Cycles:
            avg: AVG(CPC_CPC_UTCL2IU_BUSY)
            min: MIN(CPC_CPC_UTCL2IU_BUSY)
            max: MAX(CPC_CPC_UTCL2IU_BUSY)
            unit: Cycles
            tips: 
          UTCL2 Intf Util:
            avg: AVG((((100 * CPC_CPC_UTCL2IU_BUSY) / (CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE))
              if ((CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE) != 0) else None))
            min: MIN((((100 * CPC_CPC_UTCL2IU_BUSY) / (CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE))
              if ((CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE) != 0) else None))
            max: MAX((((100 * CPC_CPC_UTCL2IU_BUSY) / (CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE))
              if ((CPC_CPC_UTCL2IU_BUSY + CPC_CPC_UTCL2IU_IDLE) != 0) else None))
            unit: pct
            tips: 
