---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 1000
  title: Compute Units - Instruction Mix
  data source:
    - metric_table:
        id: 1001
        title: Instruction Mix
        header:
          metric: Metric
          count: Count
          unit: Unit
          tips: Tips
        metric:
          VALU - Vector:
            count: AVG(((SQ_INSTS_VALU - SQ_INSTS_MFMA) / $denom))
            unit: (instr + $normUnit)
            tips: 
          VMEM:
            count: AVG(((SQ_INSTS_VMEM - SQ_INSTS_FLAT_LDS_ONLY) / $denom))
            unit: (instr + $normUnit)
            tips: 
          LDS:
            count: AVG((SQ_INSTS_LDS / $denom))
            unit: (instr + $normUnit)
            tips: 
          VALU - MFMA:
            count: AVG((SQ_INSTS_MFMA / $denom))
            unit: (instr + $normUnit)
            tips: 
          SALU:
            count: AVG((SQ_INSTS_SALU / $denom))
            unit: (instr + $normUnit)
            tips: 
          SMEM:
            count: AVG((SQ_INSTS_SMEM / $denom))
            unit: (instr + $normUnit)
            tips: 
          Branch:
            count: AVG((SQ_INSTS_BRANCH / $denom))
            unit: (instr + $normUnit)
            tips: 
          GDS:
            count: AVG((SQ_INSTS_GDS / $denom))
            unit: (instr + $normUnit)
            tips: 

    - metric_table:
        id: 1002
        title: VALU Arithmetic Instr Mix
        header:
          metric: Metric
          count: Count
          unit: Unit
          tips: Tips
        metric:
          INT32:
            count: AVG((SQ_INSTS_VALU_INT32 / $denom))
            unit: (instr + $normUnit)
            tips: 
          INT64:
            count: AVG((SQ_INSTS_VALU_INT64 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F16-ADD:
            count: AVG((SQ_INSTS_VALU_ADD_F16 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F16-MUL:
            count: AVG((SQ_INSTS_VALU_MUL_F16 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F16-FMA:
            count: AVG((SQ_INSTS_VALU_FMA_F16 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F16-Trans:
            count: AVG((SQ_INSTS_VALU_TRANS_F16 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F32-ADD:
            count: AVG((SQ_INSTS_VALU_ADD_F32 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F32-MUL:
            count: AVG((SQ_INSTS_VALU_MUL_F32 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F32-FMA:
            count: AVG((SQ_INSTS_VALU_FMA_F32 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F32-Trans:
            count: AVG((SQ_INSTS_VALU_TRANS_F32 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F64-ADD:
            count: AVG((SQ_INSTS_VALU_ADD_F64 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F64-MUL:
            count: AVG((SQ_INSTS_VALU_MUL_F64 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F64-FMA:
            count: AVG((SQ_INSTS_VALU_FMA_F64 / $denom))
            unit: (instr + $normUnit)
            tips: 
          F64-Trans:
            count: AVG((SQ_INSTS_VALU_TRANS_F64 / $denom))
            unit: (instr + $normUnit)
            tips: 
          Conversion:
            count: AVG((SQ_INSTS_VALU_CVT / $denom))
            unit: (# instr + $normUnit)
            unit: (instr + $normUnit)
            tips: 

    - metric_table:
        id: 1003
        title: VMEM Instr Mix
        header:
          type: type
          count: Count
          tips: Tips
        metric:
          Buffer Instr:
            count: AVG((TA_BUFFER_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Read:
            count: AVG((TA_BUFFER_READ_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Write:
            count: AVG((TA_BUFFER_WRITE_WAVEFRONTS_sum / $denom))
            tips: 
          Buffer Atomic:
            count: AVG((TA_BUFFER_ATOMIC_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Instr:
            count: AVG((TA_FLAT_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Read:
            count: AVG((TA_FLAT_READ_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Write:
            count: AVG((TA_FLAT_WRITE_WAVEFRONTS_sum / $denom))
            tips: 
          Flat Atomic:
            count: AVG((TA_FLAT_ATOMIC_WAVEFRONTS_sum / $denom))
            tips: 

    - metric_table:
        id: 1004
        title: MFMA Arithmetic Instr Mix
        header:
          type: type
          count: Count
          tips: Tips
        metric:
          MFMA-I8:
            count: AVG((SQ_INSTS_VALU_MFMA_I8 / SQ_WAVES))
            tips: 
          MFMA-F16:
            count: AVG((SQ_INSTS_VALU_MFMA_F16 / SQ_WAVES))
            tips: 
          MFMA-BF16:
            count: AVG((SQ_INSTS_VALU_MFMA_BF16 / SQ_WAVES))
            tips: 
          MFMA-F32:
            count: AVG((SQ_INSTS_VALU_MFMA_F32 / SQ_WAVES))
            tips: 
          MFMA-F64:
            count: AVG((SQ_INSTS_VALU_MFMA_F64 / SQ_WAVES))
            tips: 
